### ISSUE TITLE
Gateway Service HTTP Errors

### ISSUE THREAD

**Issue by j** [mercurius-js/mercurius#543] opened 2021-07-28 19:56 UTC
It looks like the Mercurius Gateway service expects "errors" to exist in the response, however, if I have a fastify plugin that throws an error before it ever hits GraphQL, then the gateway emits an error.

```json
{
  "errors": [
    {
      "message": "Cannot read property 'profile' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "profile"
      ]
    }
  ],
  "data": null
}
```

It might be nice if Mercurius handled common HTTP errors (Unauthorized, Forbidden, etc) so that it just emits that error on those types of exceptions, or if each gateway service could configure it's response to format the error if it exists.

**Comment by mcollina** [comment] 2021-07-28 20:19
Sure thing! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by sameer-coder** [comment] 2022-01-12 13:40
@j I guess these http errors can be handled using a custom `errorFormatter` (https://mercurius.dev/#/docs/api/options?id=error-formatter). Have you tried it?

**Comment by sameer-coder** [comment] 2022-01-19 06:47
@mcollina Do you think we should we should change the error implementation in mercurius to accommodate these http errors or leave it for now since the same can be achieved using the `errorFormatter`?

**Comment by mcollina** [comment] 2022-01-19 07:16
I think some minimal change is needed, the described error is not a good DX. At a minimum, we should   avoid that: make sure that we support the errors property to not be there.

I'm unsure we should add specific handling of http status codes.

**Comment by sameer-coder** [comment] 2022-01-27 14:37
@mcollina Do you mean we should remove the `errors` property if the error is thrown by a fastify-plugin before the request reaches GraphQL?

**Comment by mcollina** [comment] 2022-01-27 15:17
Let me close this issue as I do not have much time to scope it.

**Comment by sameer-coder** [comment] 2022-01-31 11:35
@j can you please provide a repo that reproduces the issue?

**Closed** 2022-09-02 12:15 UTC
Labels: enhancement, good first issue
