### ISSUE TITLE
Subscription Gateway: Connection is not ready

### ISSUE THREAD

**Issue by darrenfurr** [mercurius-js/mercurius#493] opened 2021-05-17 14:59 UTC
Occasionally when starting the subscription gateway I receive:
```
{
    "name": "FormatedError",
    "message": "Unknown error",
    "originalError": "Connection is not ready"
}
```

I am also seeing this in my deployed version if I do a mid-day deployment.

I have to restart the gateway to resolve this issue. Any ideas what's going on here? 
I'm happy to do a PR if someone can point me in the right direction.

**Comment by mcollina** [comment] 2021-05-17 22:29
It would recommend to start writing a small test to reproduce the problem. Then use the debugger and console.log to find out where the problem is.

**Comment by darrenfurr** [comment] 2021-06-03 21:11
@mcollina - OK...after researching this further. This issue was caused by my `onConnect` function doing a `throw new AuthenticationError`. This was a port from our Apollo implementation.

It appears that the Apollo implementation allows: 
``` if the return value is an object, its elements will be added to the context. return false or throw an exception to reject the connection.```

Reference: https://github.com/apollographql/subscriptions-transport-ws

I've changed our code to just return if the JWT cannot be verified.

**Comment by mcollina** [comment] 2021-06-05 07:29
Amazing research? Would you like to send a PR to handle the case where that function throws?

**Comment by darrenfurr** [comment] 2021-06-18 16:52
@mcollina - I'm still investigating this issue. I am still seeing Connection is not Ready occasionally in our release candidate environment. I'm running 2 gateway pods behind an ALB.

**Comment by mcollina** [comment] 2021-06-18 18:50
Let us know of your fundings!!

**Comment by darrenfurr** [comment] 2021-07-15 16:36
@mcollina - more research on this...We are using Horizontal Pod Autoscaler to scale-out our services. It appears that when that happens the subscriptionClient in the gateway does not know to reconnect. If I keep all the HPAs at a static value, then everything works great. 

Any ideas where I can add some reconnect logic in the gateway subscriptionClient?

**Comment by mcollina** [comment] 2021-07-16 08:32
You should add it here: https://github.com/mercurius-js/mercurius/blob/9084eab681fb4fd480a11935d8997cd215904f1e/lib/subscription-client.js#L56

**Comment by tiagoheliob** [comment] 2022-01-25 14:27
@darrenfurr is it still an issue? could you please set up an example repo?

**Comment by darrenfurr** [comment] 2022-01-25 16:59
@tiagoheliob - I am not sure. We were having so many problems with the Subscription Gateway in front of our load-balancer that we moved away from it. We are now connecting directly to the graphql servers hosting the subscriptions.

**Comment by tiagoheliob** [comment] 2022-01-25 17:21
@darrenfurr thanks for the quick reply, on this case, I believe we can close this issue for now since it doesn't seem to be directly related to the initial topic.

**Closed** 2022-01-25 17:25 UTC
Labels: help wanted, good first issue

**Comment by mcollina** [comment] 2022-01-25 17:28
@tiagoheliob I think we should check/implement some reconnection logic in Mercurius. Could you take a look?

**Comment by tiagoheliob** [comment] 2022-01-25 19:25
@mcollina sure, i'll take a look
