### ISSUE TITLE
[Feat] Custom execution function

### ISSUE THREAD

**Issue by artecoop** [mercurius-js/mercurius#303] opened 2020-10-06 08:53 UTC
Hello all!

I'm here to ask if is possible, in future release of this lib, to have access to a custom execution function. This will be useful for a better integration with [GraphQL Modules](https://github.com/Urigo/graphql-modules) for example.

I'll attach here the issue opened in that repo for cross reference.
https://github.com/Urigo/graphql-modules/issues/1366

**Comment by mcollina** [comment] 2020-10-06 09:10
Thanks for reporting, this is a duplicate of https://github.com/mercurius-js/mercurius/issues/278.

**Closed by mcollina** 2020-10-06 09:10 UTC
